language: node_js
node_js:
  - '10.12.0'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn install
script:
  - yarn build
